# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasShaperDialog
                                 A QGIS plugin
 Plugin for las files.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-17
        git sha              : $Format:%H$
        copyright            : (C) 2023 by d4mp3
        email                : pszdam@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog
from .las_shaper_functions import *
from .classification_codes import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'las_shaper_dialog_base.ui'))


class LasShaperDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(LasShaperDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Extract Las Class Frame
        self.cbClassificationCode.addItems(CLASSIFICATION_CODES.values())
        self.tbInputELC.clicked.connect(self.__get_elc_input)
        self.tbOutputELC.clicked.connect(self.__set_elc_output)
        self.pbELC.clicked.connect(self.__run_extract_las_class)


    def __get_elc_input(self):
        input_path = QFileDialog.getOpenFileNames(self, "Open Files", "", "LAS Files (*.las)")
        if len(input_path[0]) != 0:
            input_path = input_path[0]
            input_path = '; '.join(input_path)
            self.leInputELC.setText(str(input_path))


    def __set_elc_output(self):
        output_path = QFileDialog.getSaveFileName(self, "Save File", "", "LAS File (*.las)")
        if len(output_path[0]) != 0:
            self.leOutputELC.setText(str(output_path[0]))


    def __run_extract_las_class(self):
        las_class = [list(CLASSIFICATION_CODES.values()).index(self.cbClassificationCode.currentText())]
        if self.tbInputELC != '' and self.tbOutputELC != '':
            extract_las_class(self.leInputELC.text(), self.leOutputELC.text(), las_class)
        else:
            print('invalid input or output path')

